package annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/** Used to mark Message (non-abstract) subclasses so they can be registered in the MessageTypeRegistry class when
 *  generated by the MessageTypeRegistryProcessor. */
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface AutoRegisterMessage {
}